---
# MD003 heading-style - Allow both ATX and setext heading styles
MD003: false
# MD013 line-length - Line length
MD013:
  line_length: 120
# MD033 no-inline-html - Inline HTML
MD033:
  allowed_elements: [details, reasoning]
# MD046 code-block-style - Code block style
MD046:
  style: consistent
